language: php

php:
    - 5.4

install:
  ## Mysql configuration
  - "cp tests/config.inc.sample.php tests/config.inc.php"
  - "mysql -e 'CREATE DATABASE testspicorm;'"

script:
    ## ATOUM
    - php tests/launcher.php

notifications:
  irc: "chat.freenode.net#picORM"

env:
  - DB=mysql
