language: php

php:
    - 5.3
    - 5.4
    - 5.5

install:
  - "cp tests/config.inc.sample.php tests/config.inc.php"
  - "mysql -e 'CREATE DATABASE testspicorm;'"

script:
    - php tests/launcher.php

env:
  - DB=mysql
